name = "sleepmon-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"
workers_dev = true

# Cron cleanup every 6 hours
[triggers]
crons = ["0 */6 * * *"]

# === Bindings (fill database_id after `wrangler d1 list`) ===
[[d1_databases]]
binding = "DB"
database_name = "sleepmon-db"
database_id = "a112f28f-3391-499b-943a-5e498012142c"

[[r2_buckets]]
binding = "AUDIO"
bucket_name = "sleepmon-audio"
